version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  type_checker = "mypy"
  runtime_version = "3.x.x"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]
