name: Build ChangeLog

on:
  workflow_run:
    workflows: ["Sync Version"]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  build_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython packaging pytz

      - name: Build Changelog
        run: |
          python .github/release_produce.py
  
      - name: Get Version
        run: echo "VERSION=$(<version)" >> $GITHUB_ENV
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body_path: changelog.md