name: Test Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test-correct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test action
        uses: szymansd/auto-release-notes@v1.0.1
        with:
          github_token: ${{ secrets.CreateReleaseNoteToken }}
          description_template_filepath: './.github/templates/deployment.md'
