name: BuildToolDelta
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pyinstaller -F ToolDelta.py
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ToolDelta
          tag_name: v1.0.0
          title: Release v1.0.0
          body: This is the first release of ToolDelta
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
