name: Build and Publish Python Package



on:
  workflow_run:
    workflows: ["Sync Version"]
    types:
      - completed
  workflow_dispatch: {}



jobs:
  Publisher:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install poetry

    - name: Build and Publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry version $(cat version)
        poetry build
        poetry publish