name: Publish to PyPI

on:
  push:
    branches: [ main ]
    paths:
      - "version"
  workflow_dispatch: {}

jobs:
  build-n-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v2.0
      with:
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
